url: http://oziegamma.github.io/
baseurl: /SUMMIT-Website/

# Site settings
title: SUMMIT
email: your-email@domain.com
description: "Website for the SUMMIT association. SUMMIT is the association of student studying management of technology at EPFL."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Oswald Maskens
  pic: oswald
  position: President
  social:
    - title: linkedin
      url: https://ch.linkedin.com/in/oswaldmaskens

- name: Alexis Frentz
  pic: alexis
  position: Board member
  social:
    - title: linkedin
      url: https://fr.linkedin.com/in/alexisfrentz

- name: Maria Kuleshova
  pic: maria
  position: Board member
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/maria-kuleshova-0527a8a2


- name: Renaud Lafond Rive
  pic: renaud
  position: Accounts Verificator
  social:
    - title: linkedin
      url: https://ch.linkedin.com/in/rlafondrive
      

- name: Romain Kirchhoff
  pic: romain
  position: Accounts Verificator
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/romain-kirchhoff-15a80062
      
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: "SUMMIT, Association des étudiants en MTE de l'EPFL"
  - line: "1015 Lausanne"

# Build settings
markdown: kramdown
permalink: pretty