url: https://sme.epfl.ch/
baseurl: /

# Site settings
title: SME
email: sme@epfl.ch
description: "Website for the SME association. SME is the association of student studying management of technology at EPFL."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/sme.epfl/

# Postal address (add as many lines as necessary)
address:
  - line: "SME, Association des étudiants en MTE de l'EPFL"
  - line: "1015 Lausanne"
  
statutes:
  url: "https://drive.google.com/file/d/0B-DLL4FEK1esbGlrSzNyQUJSeU0/view"

# Build settings
markdown: kramdown
permalink: pretty

# Open source attributions
attributions:
  - name: "Agency theme by Start Bootstrap"
    url: "http://startbootstrap.com/template-overviews/agency/"
    
  - name: "Agency them post by GitHub user y7kim"
    url: "https://github.com/y7kim/agency-jekyll-theme"
    
  - name: "Bootstrap"
    url: "https://getbootstrap.com/"
    
  - name: "JQuery"
    url: "https://jquery.com"
  
  - name: "Jekyll"
    url: "https://jekyllrb.com/"
  
  - name: "Formspree"
    url: "https://formspree.io"
