url: http://oziegamma.github.io/
baseurl: /SUMMIT-Website/

# Site settings
title: SUMMIT
email: your-email@domain.com
description: "Website for the SUMMIT association. SUMMIT is the association of student studying management of technology at EPFL."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Oswald Maskens
  pic: oswald
  position: President
  social:
    - title: linkedin
      url: https://ch.linkedin.com/in/oswaldmaskens

- name: Alexis Frentz
  pic: alexis
  position: Board member
  social:
    - title: linkedin
      url: https://fr.linkedin.com/in/alexisfrentz

- name: Maria Kuleshova
  pic: maria
  position: Board member
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/maria-kuleshova-0527a8a2


- name: Renaud Lafond Rive
  pic: renaud
  position: Accounts Verificator
  social:
    - title: linkedin
      url: https://ch.linkedin.com/in/rlafondrive
      

- name: Romain Kirchhoff
  pic: romain
  position: Accounts Verificator
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/romain-kirchhoff-15a80062
      
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/summitepfl/

# Postal address (add as many lines as necessary)
address:
  - line: "SUMMIT, Association des étudiants en MTE de l'EPFL"
  - line: "1015 Lausanne"
  
statutes:
  url: "https://ue1qlg.bn1301.livefilestore.com/y3m4rXj3DW7hiMCYv9VOunDo3JWjAtrc3Nos4R6ctt3CRtbQ9x3iiZi4o64sdS5zDsutmi9s5NJ_9miLMHP3dxt_vZJaIgcme9VcuPbgA39s823pHrkBvQz7S7jtyOTMALlwIQ_v1ed2Jojg6hrPVuwgg/Statuts_17_dec_2015.pdf?psid=1"

# Build settings
markdown: kramdown
permalink: pretty

# Open source attributions
attributions:
  - name: "Agency theme by Start Bootstrap"
    url: "http://startbootstrap.com/template-overviews/agency/"
    
  - name: "Agency them post by GitHub user y7kim"
    url: "https://github.com/y7kim/agency-jekyll-theme"
    
  - name: "Bootstrap"
    url: "https://getbootstrap.com/"
    
  - name: "JQuery"
    url: "https://jquery.com"