url: http://sme.epfl.ch/
baseurl: /

# Site settings
title: SME
email: sme@epfl.ch
description: "Website for the SME association. SME is the association of student studying management of technology at EPFL."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: A00
  secondary: 900  
  secondary-dark: 333

# Team names, titles and social links
team:
- name: Yves Robert-Tissot
  pic: yvest
  position: President
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/yves-robert-tissot-8ba473131

- name: Nico Hübner
  pic: nico
  position: Vice president
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/nicohuebner

- name: Yves Baudet
  pic: yvesb
  position: Treasurer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/yves-baudet-bab066a9
      
sponsors:
  #- name: aetuts
  #  logo: aetuts
    
  #- name: envato
  #  logo: envato
      
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/sme.epfl/

# Postal address (add as many lines as necessary)
address:
  - line: "SME, Association des étudiants en MTE de l'EPFL"
  - line: "1015 Lausanne"
  
statutes:
  url: "https://drive.google.com/file/d/0B-DLL4FEK1esbGlrSzNyQUJSeU0/view"

# Build settings
markdown: kramdown
permalink: pretty

# Open source attributions
attributions:
  - name: "Agency theme by Start Bootstrap"
    url: "http://startbootstrap.com/template-overviews/agency/"
    
  - name: "Agency them post by GitHub user y7kim"
    url: "https://github.com/y7kim/agency-jekyll-theme"
    
  - name: "Bootstrap"
    url: "https://getbootstrap.com/"
    
  - name: "JQuery"
    url: "https://jquery.com"
  
  - name: "Jekyll"
    url: "https://jekyllrb.com/"
  
  - name: "Formspree"
    url: "https://formspree.io"
